/* ============================================================
   FICHES PERSONNAGES — HONKAI: STAR RAIL, WUTHERING WAVES, NTE
   Relevé du 16 septembre 2026.
   - HSR  : noms, éléments et voies en français, tirés des fichiers du jeu
            (dépôt StarRailRes, mis à jour fin août 2026), recoupés avec prydwen.gg.
   - WuWa : liste identique sur deux sites (gamevika.com, mmoculture.com, version 3.6).
            Libellés d'armes traduits : à vérifier avec la version française du jeu.
   - NTE  : attributs identiques sur deux sites (kaiden.gg, zeroluck.gg).
            Rang (S = 5, A = 4) et type d'arc d'après zeroluck.gg ; rang laissé
            vide pour Zero et Chiz (personnages gratuits, rang non confirmé).
   Pas de bio ni de build de référence : rien n'est inventé. Ajoute-les
   au même format que data.js (champs bio / build) quand ils sont vérifiés.

   IMAGES : dépose le portrait dans le dossier du jeu (hsr/, wuwa/, nte/),
   nommé comme l'id (ex. hsr/kafka.png), puis ajoute l'id dans la liste
   IMAGES_... correspondante. Extension libre (.png, .jpg, .jpeg, .webp).
   ============================================================ */

const IMAGES_HSR = [];
const IMAGES_WUWA = [];
const IMAGES_NTE = [];

const PERSONNAGES_HSR = [
  {"id": "march-7th", "nom": "March 7th", "element": "Glace", "arme": "Préservation", "rarete": 4},
  {"id": "dan-heng", "nom": "Dan Heng", "element": "Vent", "arme": "Chasse", "rarete": 4},
  {"id": "himeko", "nom": "Himeko", "element": "Feu", "arme": "Érudition", "rarete": 5},
  {"id": "welt", "nom": "Welt", "element": "Imaginaire", "arme": "Nihilité", "rarete": 5},
  {"id": "kafka", "nom": "Kafka", "element": "Foudre", "arme": "Nihilité", "rarete": 5},
  {"id": "louve-d-argent", "nom": "Louve d'argent", "element": "Quantique", "arme": "Nihilité", "rarete": 5},
  {"id": "arlan", "nom": "Arlan", "element": "Foudre", "arme": "Destruction", "rarete": 4},
  {"id": "asta", "nom": "Asta", "element": "Feu", "arme": "Harmonie", "rarete": 4},
  {"id": "herta", "nom": "Herta", "element": "Glace", "arme": "Érudition", "rarete": 4},
  {"id": "saber", "nom": "Saber", "element": "Vent", "arme": "Destruction", "rarete": 5},
  {"id": "archer", "nom": "Archer", "element": "Quantique", "arme": "Chasse", "rarete": 5},
  {"id": "bronya", "nom": "Bronya", "element": "Vent", "arme": "Harmonie", "rarete": 5},
  {"id": "seele", "nom": "Seele", "element": "Quantique", "arme": "Chasse", "rarete": 5},
  {"id": "serval", "nom": "Serval", "element": "Foudre", "arme": "Érudition", "rarete": 4},
  {"id": "gepard", "nom": "Gepard", "element": "Glace", "arme": "Préservation", "rarete": 5},
  {"id": "natasha", "nom": "Natasha", "element": "Physique", "arme": "Abondance", "rarete": 4},
  {"id": "pela", "nom": "Pela", "element": "Glace", "arme": "Nihilité", "rarete": 4},
  {"id": "clara", "nom": "Clara", "element": "Physique", "arme": "Destruction", "rarete": 5},
  {"id": "sampo", "nom": "Sampo", "element": "Vent", "arme": "Nihilité", "rarete": 4},
  {"id": "hook", "nom": "Hook", "element": "Feu", "arme": "Destruction", "rarete": 4},
  {"id": "lynx", "nom": "Lynx", "element": "Quantique", "arme": "Abondance", "rarete": 4},
  {"id": "luka", "nom": "Luka", "element": "Physique", "arme": "Nihilité", "rarete": 4},
  {"id": "topaz-et-compti", "nom": "Topaz et Compti", "element": "Feu", "arme": "Chasse", "rarete": 5},
  {"id": "qingque", "nom": "Qingque", "element": "Quantique", "arme": "Érudition", "rarete": 4},
  {"id": "tingyun", "nom": "Tingyun", "element": "Foudre", "arme": "Harmonie", "rarete": 4},
  {"id": "luocha", "nom": "Luocha", "element": "Imaginaire", "arme": "Abondance", "rarete": 5},
  {"id": "jing-yuan", "nom": "Jing Yuan", "element": "Foudre", "arme": "Érudition", "rarete": 5},
  {"id": "blade", "nom": "Blade", "element": "Vent", "arme": "Destruction", "rarete": 5},
  {"id": "sushang", "nom": "Sushang", "element": "Physique", "arme": "Chasse", "rarete": 4},
  {"id": "yukong", "nom": "Yukong", "element": "Imaginaire", "arme": "Harmonie", "rarete": 4},
  {"id": "fu-xuan", "nom": "Fu Xuan", "element": "Quantique", "arme": "Préservation", "rarete": 5},
  {"id": "yanqing", "nom": "Yanqing", "element": "Glace", "arme": "Chasse", "rarete": 5},
  {"id": "guinaifen", "nom": "Guinaifen", "element": "Feu", "arme": "Nihilité", "rarete": 4},
  {"id": "bailu", "nom": "Bailu", "element": "Foudre", "arme": "Abondance", "rarete": 5},
  {"id": "jingliu", "nom": "Jingliu", "element": "Glace", "arme": "Destruction", "rarete": 5},
  {"id": "dan-heng-imbibitor-lunae", "nom": "Dan Heng • Imbibitor Lunae", "element": "Imaginaire", "arme": "Destruction", "rarete": 5},
  {"id": "xueyi", "nom": "Xueyi", "element": "Quantique", "arme": "Destruction", "rarete": 4},
  {"id": "hanya", "nom": "Hanya", "element": "Physique", "arme": "Harmonie", "rarete": 4},
  {"id": "huohuo", "nom": "Huohuo", "element": "Vent", "arme": "Abondance", "rarete": 5},
  {"id": "jiaoqiu", "nom": "Jiaoqiu", "element": "Feu", "arme": "Nihilité", "rarete": 5},
  {"id": "feixiao", "nom": "Feixiao", "element": "Vent", "arme": "Chasse", "rarete": 5},
  {"id": "yunli", "nom": "Yunli", "element": "Physique", "arme": "Destruction", "rarete": 5},
  {"id": "lingsha", "nom": "Lingsha", "element": "Feu", "arme": "Abondance", "rarete": 5},
  {"id": "moze", "nom": "Moze", "element": "Foudre", "arme": "Chasse", "rarete": 4},
  {"id": "march-7th-chasse", "nom": "March 7th • Chasse", "element": "Imaginaire", "arme": "Chasse", "rarete": 4},
  {"id": "peregrine", "nom": "Pérégrine", "element": "Feu", "arme": "Nihilité", "rarete": 5},
  {"id": "gallagher", "nom": "Gallagher", "element": "Feu", "arme": "Abondance", "rarete": 4},
  {"id": "argenti", "nom": "Argenti", "element": "Physique", "arme": "Érudition", "rarete": 5},
  {"id": "ruan-mei", "nom": "Ruan Mei", "element": "Glace", "arme": "Harmonie", "rarete": 5},
  {"id": "aventurine", "nom": "Aventurine", "element": "Imaginaire", "arme": "Préservation", "rarete": 5},
  {"id": "dr-ratio", "nom": "Dr Ratio", "element": "Imaginaire", "arme": "Chasse", "rarete": 5},
  {"id": "sparkle", "nom": "Sparkle", "element": "Quantique", "arme": "Harmonie", "rarete": 5},
  {"id": "cygne-noir", "nom": "Cygne noir", "element": "Vent", "arme": "Nihilité", "rarete": 5},
  {"id": "acheron", "nom": "Achéron", "element": "Foudre", "arme": "Nihilité", "rarete": 5},
  {"id": "robin", "nom": "Robin", "element": "Physique", "arme": "Harmonie", "rarete": 5},
  {"id": "luciole", "nom": "Luciole", "element": "Feu", "arme": "Destruction", "rarete": 5},
  {"id": "micha", "nom": "Micha", "element": "Glace", "arme": "Destruction", "rarete": 4},
  {"id": "sunday", "nom": "Sunday", "element": "Imaginaire", "arme": "Harmonie", "rarete": 5},
  {"id": "jade", "nom": "Jade", "element": "Quantique", "arme": "Érudition", "rarete": 5},
  {"id": "le-fossoyeur", "nom": "Le Fossoyeur", "element": "Physique", "arme": "Chasse", "rarete": 5},
  {"id": "rappa", "nom": "Rappa", "element": "Imaginaire", "arme": "Érudition", "rarete": 5},
  {"id": "le-dahlia", "nom": "Le Dahlia", "element": "Feu", "arme": "Nihilité", "rarete": 5},
  {"id": "la-grande-herta", "nom": "La Grande Herta", "element": "Glace", "arme": "Érudition", "rarete": 5},
  {"id": "aglae", "nom": "Aglaé", "element": "Foudre", "arme": "Souvenir", "rarete": 5},
  {"id": "tribbie", "nom": "Tribbie", "element": "Quantique", "arme": "Harmonie", "rarete": 5},
  {"id": "mydei", "nom": "Mydei", "element": "Imaginaire", "arme": "Destruction", "rarete": 5},
  {"id": "anaxa", "nom": "Anaxa", "element": "Vent", "arme": "Érudition", "rarete": 5},
  {"id": "cipher", "nom": "Cipher", "element": "Quantique", "arme": "Nihilité", "rarete": 5},
  {"id": "castorice", "nom": "Castorice", "element": "Quantique", "arme": "Souvenir", "rarete": 5},
  {"id": "phaenon", "nom": "Phaénon", "element": "Physique", "arme": "Destruction", "rarete": 5},
  {"id": "hyacine", "nom": "Hyacine", "element": "Vent", "arme": "Souvenir", "rarete": 5},
  {"id": "hysilens", "nom": "Hysilens", "element": "Physique", "arme": "Nihilité", "rarete": 5},
  {"id": "cerydra", "nom": "Cérydra", "element": "Vent", "arme": "Harmonie", "rarete": 5},
  {"id": "nocterna", "nom": "Nocterna", "element": "Glace", "arme": "Souvenir", "rarete": 5},
  {"id": "dan-heng-permansor-terrae", "nom": "Dan Heng • Permansor Terrae", "element": "Physique", "arme": "Préservation", "rarete": 5},
  {"id": "cyrene", "nom": "Cyrène", "element": "Glace", "arme": "Souvenir", "rarete": 5},
  {"id": "sparxie", "nom": "Sparxie", "element": "Feu", "arme": "Allégresse", "rarete": 5},
  {"id": "yao-guang", "nom": "Yao Guang", "element": "Physique", "arme": "Allégresse", "rarete": 5},
  {"id": "ashveil", "nom": "Ashveil", "element": "Foudre", "arme": "Chasse", "rarete": 5},
  {"id": "evanescia", "nom": "Evanescia", "element": "Physique", "arme": "Allégresse", "rarete": 5},
  {"id": "louve-d-argent-niv-999", "nom": "Louve d'argent Niv. 999", "element": "Imaginaire", "arme": "Allégresse", "rarete": 5},
  {"id": "blade-mortenax", "nom": "Blade Mortenax", "element": "Feu", "arme": "Nihilité", "rarete": 5},
  {"id": "rin-tohsaka", "nom": "Rin Tohsaka", "element": "Quantique", "arme": "Érudition", "rarete": 5},
  {"id": "gilgamesh", "nom": "Gilgamesh", "element": "Foudre", "arme": "Destruction", "rarete": 5},
  {"id": "himeko-nova", "nom": "Himeko • Nova", "element": "Feu", "arme": "Érudition", "rarete": 5},
  {"id": "robin-estivaria", "nom": "Robin • Estivaria", "element": "Vent", "arme": "Souvenir", "rarete": 5},
  {"id": "aventurine-croisette", "nom": "Aventurine • Croisette", "element": "Quantique", "arme": "Allégresse", "rarete": 5},
  {"id": "pionnier-destruction", "nom": "Pionnier • Destruction", "element": "Physique", "arme": "Destruction", "rarete": 5},
  {"id": "pionnier-preservation", "nom": "Pionnier • Préservation", "element": "Feu", "arme": "Préservation", "rarete": 5},
  {"id": "pionnier-harmonie", "nom": "Pionnier • Harmonie", "element": "Imaginaire", "arme": "Harmonie", "rarete": 5},
  {"id": "pionnier-souvenir", "nom": "Pionnier • Souvenir", "element": "Glace", "arme": "Souvenir", "rarete": 5},
  {"id": "pionnier-allegresse", "nom": "Pionnier • Allégresse", "element": "Foudre", "arme": "Allégresse", "rarete": 5}
];

const PERSONNAGES_WUWA = [
  {"id": "aalto", "nom": "Aalto", "element": "Aero", "arme": "Pistolets", "rarete": 4},
  {"id": "yangyang", "nom": "Yangyang", "element": "Aero", "arme": "Épée", "rarete": 4},
  {"id": "cartethyia", "nom": "Cartethyia", "element": "Aero", "arme": "Épée", "rarete": 5},
  {"id": "ciaccona", "nom": "Ciaccona", "element": "Aero", "arme": "Pistolets", "rarete": 5},
  {"id": "iuno", "nom": "Iuno", "element": "Aero", "arme": "Gantelets", "rarete": 5},
  {"id": "jianxin", "nom": "Jianxin", "element": "Aero", "arme": "Gantelets", "rarete": 5},
  {"id": "jiyan", "nom": "Jiyan", "element": "Aero", "arme": "Grande lame", "rarete": 5},
  {"id": "qingxiao", "nom": "Qingxiao", "element": "Aero", "arme": "Épée", "rarete": 5},
  {"id": "qiuyuan", "nom": "Qiuyuan", "element": "Aero", "arme": "Épée", "rarete": 5},
  {"id": "rover-aero", "nom": "Rover (Aero)", "element": "Aero", "arme": "Épée", "rarete": 5},
  {"id": "sigrika", "nom": "Sigrika", "element": "Aero", "arme": "Gantelets", "rarete": 5},
  {"id": "baizhi", "nom": "Baizhi", "element": "Glacio", "arme": "Rectifieur", "rarete": 4},
  {"id": "sanhua", "nom": "Sanhua", "element": "Glacio", "arme": "Épée", "rarete": 4},
  {"id": "youhu", "nom": "Youhu", "element": "Glacio", "arme": "Gantelets", "rarete": 4},
  {"id": "carlotta", "nom": "Carlotta", "element": "Glacio", "arme": "Pistolets", "rarete": 5},
  {"id": "hiyuki", "nom": "Hiyuki", "element": "Glacio", "arme": "Épée", "rarete": 5},
  {"id": "lingyang", "nom": "Lingyang", "element": "Glacio", "arme": "Gantelets", "rarete": 5},
  {"id": "lucilla", "nom": "Lucilla", "element": "Glacio", "arme": "Rectifieur", "rarete": 5},
  {"id": "suisui", "nom": "Suisui", "element": "Glacio", "arme": "Rectifieur", "rarete": 5},
  {"id": "zhezhi", "nom": "Zhezhi", "element": "Glacio", "arme": "Rectifieur", "rarete": 5},
  {"id": "buling", "nom": "Buling", "element": "Electro", "arme": "Rectifieur", "rarete": 4},
  {"id": "lumi", "nom": "Lumi", "element": "Electro", "arme": "Grande lame", "rarete": 4},
  {"id": "yuanwu", "nom": "Yuanwu", "element": "Electro", "arme": "Gantelets", "rarete": 4},
  {"id": "augusta", "nom": "Augusta", "element": "Electro", "arme": "Grande lame", "rarete": 5},
  {"id": "calcharo", "nom": "Calcharo", "element": "Electro", "arme": "Grande lame", "rarete": 5},
  {"id": "rebecca", "nom": "Rebecca", "element": "Electro", "arme": "Pistolets", "rarete": 5},
  {"id": "rover-electro", "nom": "Rover (Electro)", "element": "Electro", "arme": "Épée", "rarete": 5},
  {"id": "xiangli-yao", "nom": "Xiangli Yao", "element": "Electro", "arme": "Gantelets", "rarete": 5},
  {"id": "yinlin", "nom": "Yinlin", "element": "Electro", "arme": "Rectifieur", "rarete": 5},
  {"id": "chixia", "nom": "Chixia", "element": "Fusion", "arme": "Pistolets", "rarete": 4},
  {"id": "mortefi", "nom": "Mortefi", "element": "Fusion", "arme": "Pistolets", "rarete": 4},
  {"id": "aemeath", "nom": "Aemeath", "element": "Fusion", "arme": "Épée", "rarete": 5},
  {"id": "brant", "nom": "Brant", "element": "Fusion", "arme": "Épée", "rarete": 5},
  {"id": "changli", "nom": "Changli", "element": "Fusion", "arme": "Épée", "rarete": 5},
  {"id": "denia", "nom": "Denia", "element": "Fusion", "arme": "Rectifieur", "rarete": 5},
  {"id": "encore", "nom": "Encore", "element": "Fusion", "arme": "Rectifieur", "rarete": 5},
  {"id": "galbrena", "nom": "Galbrena", "element": "Fusion", "arme": "Pistolets", "rarete": 5},
  {"id": "jingran", "nom": "Jingran", "element": "Fusion", "arme": "Grande lame", "rarete": 5},
  {"id": "lupa", "nom": "Lupa", "element": "Fusion", "arme": "Grande lame", "rarete": 5},
  {"id": "mornye", "nom": "Mornye", "element": "Fusion", "arme": "Grande lame", "rarete": 5},
  {"id": "danjin", "nom": "Danjin", "element": "Havoc", "arme": "Épée", "rarete": 4},
  {"id": "taoqi", "nom": "Taoqi", "element": "Havoc", "arme": "Grande lame", "rarete": 4},
  {"id": "camellya", "nom": "Camellya", "element": "Havoc", "arme": "Épée", "rarete": 5},
  {"id": "cantarella", "nom": "Cantarella", "element": "Havoc", "arme": "Rectifieur", "rarete": 5},
  {"id": "chisa", "nom": "Chisa", "element": "Havoc", "arme": "Grande lame", "rarete": 5},
  {"id": "phrolova", "nom": "Phrolova", "element": "Havoc", "arme": "Rectifieur", "rarete": 5},
  {"id": "roccia", "nom": "Roccia", "element": "Havoc", "arme": "Gantelets", "rarete": 5},
  {"id": "rover-havoc", "nom": "Rover (Havoc)", "element": "Havoc", "arme": "Épée", "rarete": 5},
  {"id": "yangyang-xuanling", "nom": "Yangyang: Xuanling", "element": "Havoc", "arme": "Épée", "rarete": 5},
  {"id": "jinhsi", "nom": "Jinhsi", "element": "Spectro", "arme": "Grande lame", "rarete": 5},
  {"id": "lucy", "nom": "Lucy", "element": "Spectro", "arme": "Pistolets", "rarete": 5},
  {"id": "luuk-herssen", "nom": "Luuk Herssen", "element": "Spectro", "arme": "Gantelets", "rarete": 5},
  {"id": "lynae", "nom": "Lynae", "element": "Spectro", "arme": "Pistolets", "rarete": 5},
  {"id": "phoebe", "nom": "Phoebe", "element": "Spectro", "arme": "Rectifieur", "rarete": 5},
  {"id": "rover-spectro", "nom": "Rover (Spectro)", "element": "Spectro", "arme": "Épée", "rarete": 5},
  {"id": "shorekeeper", "nom": "Shorekeeper", "element": "Spectro", "arme": "Rectifieur", "rarete": 5},
  {"id": "verina", "nom": "Verina", "element": "Spectro", "arme": "Rectifieur", "rarete": 5},
  {"id": "zani", "nom": "Zani", "element": "Spectro", "arme": "Gantelets", "rarete": 5}
];

const PERSONNAGES_NTE = [
  {"id": "adler", "nom": "Adler", "element": "Incantation", "arme": "Condensat", "rarete": 4, "role": "Survie"},
  {"id": "aurelia", "nom": "Aurelia", "element": "Psyche", "arme": "Plasma", "rarete": 4, "role": "DPS"},
  {"id": "baicang", "nom": "Baicang", "element": "Incantation", "arme": "Condensat", "rarete": 5, "role": "DPS"},
  {"id": "chaos", "nom": "Chaos", "element": "Lakshana", "arme": "Condensat", "rarete": 5, "role": "DPS"},
  {"id": "chiz", "nom": "Chiz", "element": "Cosmos", "arme": "Gaz", "rarete": null, "role": "DPS"},
  {"id": "daffodill", "nom": "Daffodill", "element": "Chaos", "arme": "Liquide", "rarete": 5, "role": "DPS"},
  {"id": "edgar", "nom": "Edgar", "element": "Cosmos", "arme": "Liquide", "rarete": 4, "role": "Survie"},
  {"id": "fadia", "nom": "Fadia", "element": "Psyche", "arme": "Condensat", "rarete": 5, "role": "Survie"},
  {"id": "haniel", "nom": "Haniel", "element": "Psyche", "arme": "Solide", "rarete": 4, "role": "Soutien"},
  {"id": "hathor", "nom": "Hathor", "element": "Lakshana", "arme": "Plasma", "rarete": 5, "role": "DPS"},
  {"id": "hotori", "nom": "Hotori", "element": "Cosmos", "arme": "Solide", "rarete": 5, "role": "Soutien"},
  {"id": "iroi", "nom": "Iroi", "element": "Anima", "arme": "Liquide", "rarete": 5, "role": "Survie"},
  {"id": "jiuyuan", "nom": "Jiuyuan", "element": "Anima", "arme": "Solide", "rarete": 5, "role": "DPS"},
  {"id": "lacrimosa", "nom": "Lacrimosa", "element": "Chaos", "arme": "Liquide", "rarete": 5, "role": "DPS"},
  {"id": "linko", "nom": "Linko", "element": "Anima", "arme": "Plasma", "rarete": 5, "role": "DPS"},
  {"id": "mint", "nom": "Mint", "element": "Anima", "arme": "Liquide", "rarete": 4, "role": "DPS"},
  {"id": "nanally", "nom": "Nanally", "element": "Anima", "arme": "Plasma", "rarete": 5, "role": "DPS"},
  {"id": "sakiri", "nom": "Sakiri", "element": "Incantation", "arme": "Gaz", "rarete": 5, "role": "Soutien"},
  {"id": "shinku", "nom": "Shinku", "element": "Cosmos", "arme": "Condensat", "rarete": 5, "role": "DPS"},
  {"id": "skia", "nom": "Skia", "element": "Lakshana", "arme": "Gaz", "rarete": 4, "role": "DPS"},
  {"id": "zankou", "nom": "Zankou", "element": "Incantation", "arme": "Gaz", "rarete": 5, "role": "DPS"},
  {"id": "zero", "nom": "Zero", "element": "Cosmos", "arme": "Solide", "rarete": null, "role": "DPS"}
];
